-- Legacy remote schema snapshot captured 2025-11-28.
-- This was the original schema from before the numbered migration system (001-011) was established.
-- All tables, constraints, indexes, triggers, policies, and grants it defined are fully
-- covered by migrations 001_initial_schema.sql through 011_rls_audit.sql.
-- This file is kept as a tracking placeholder so local and remote migration history stay in sync.
-- It is intentionally a no-op on local replay.
